In [2]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
type(mylist)

list

In [5]:
np.array(mylist)

array([1, 2, 3])

In [6]:
array = np.array(mylist)

In [7]:
print(type(array))

<class 'numpy.ndarray'>


In [8]:
mylist = [[1,2,3],[4,5,6],[7,8,9]]


In [10]:
matrix = np.array(mylist)
print(matrix)
print(type(matrix))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
np.ones((4,10)) + 4

array([[5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

In [18]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [20]:
len(np.linspace(0,10,20))

20

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
np.random.rand(5,5)

array([[0.78327708, 0.48876679, 0.99709668, 0.35931551, 0.24118643],
       [0.63769129, 0.73272494, 0.93451187, 0.22017665, 0.7722185 ],
       [0.10078778, 0.32716238, 0.35954184, 0.93825801, 0.62352813],
       [0.22945108, 0.3035784 , 0.30871786, 0.24247133, 0.2487329 ],
       [0.0313605 , 0.63714516, 0.81896806, 0.08260377, 0.77874811]])

In [23]:
np.random.randn(10)

array([ 0.64674295, -0.79513021, -2.49105023, -0.32537269,  0.81000204,
       -0.73085112,  0.44927193,  0.1020071 ,  0.24767713, -0.81812999])

In [24]:
np.random.randint(1,100,10)

array([11, 96,  6, 77, 40,  9, 38, 81, 70, 66])

In [27]:
np.random.seed(555)
np.random.rand(4)

array([0.71783409, 0.04785513, 0.94447198, 0.68638004])

In [31]:
arr = np.arange(25)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr = np.random.randint(0,50,10)

In [34]:
ranarr

array([41, 48, 32, 20, 22, 22, 10, 21, 27, 28])

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
ranarr.max()

48

In [38]:
ranarr.min()

10

In [39]:
ranarr.argmax()

1

In [40]:
ranarr.argmin()

6

In [41]:
ranarr.dtype

dtype('int32')

## Indexing and Selection

In [42]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [47]:
new_arr = arr/2

In [48]:
new_arr

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
slice_of_arr = arr[0:6]

In [51]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [53]:
# Reassigns all values to the original value
slice_of_arr[:] = 99
print(slice_of_arr)

[99 99 99 99 99 99]


In [55]:
arr_copy = arr.copy()
arr_copy[:] = 1000
print(arr_copy)
print(arr)

[1000 1000 1000 1000 1000 1000 1000 1000 1000 1000 1000]
[99 99 99 99 99 99  6  7  8  9 10]


### 2D Arrays

In [56]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [57]:
arr_2d.shape

(3, 3)

In [58]:
arr_2d[1,1]

25

In [61]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### Comparison Selection

In [62]:
arr = np.arange(1,11)

In [63]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
bool_arr = arr > 4

In [65]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [66]:
arr[ arr  > 4]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr<= 6]

array([1, 2, 3, 4, 5, 6])

## Operations

In [68]:
arr = np.arange(0,11)

In [69]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [70]:
(arr + 2) / 100

array([0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11, 0.12])

In [71]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [72]:
1 / arr

C:\Users\ila66\AppData\Local\Temp/ipykernel_11020/1528351372.py:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [73]:
arr / arr

C:\Users\ila66\AppData\Local\Temp/ipykernel_11020/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [76]:
arr_2d = np.array( [[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)
print(arr_2d.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [78]:
arr_2d.sum()

78

In [79]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [80]:
arr_2d.sum(axis=1)

array([10, 26, 42])

## Excercises