## Series with Pandas

In [1]:
import numpy as np
import pandas as pd

In [3]:
labels = ["a","b","c"]

In [4]:
mylist = [10,20,30]

In [5]:
array = np.array(mylist)

In [6]:
d = {"a":10,"b":20,"c":30}

In [9]:
pd.Series(data=array, index=labels)

a    10
b    20
c    30
dtype: int32

In [10]:
ser1 = pd.Series(data=[1,2,3,4],index=['USA','Germany',"USSR","Japan"])

print(ser1)

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64


In [11]:
ser1['USA']

1

In [14]:
ser2 = pd.Series(data=[1,4,5,6],index=['USA','Germany',"Italy","Japan"])

print(ser2)

USA        1
Germany    4
Italy      5
Japan      6
dtype: int64


In [15]:
ser1 + ser2

Germany     6.0
Italy       NaN
Japan      10.0
USA         2.0
USSR        NaN
dtype: float64

## DataFrames

In [16]:
from numpy.random import randn

In [18]:
np.random.seed(101)
rand_mat = randn(5,4)
print(rand_mat)

[[ 2.70684984  0.62813271  0.90796945  0.50382575]
 [ 0.65111795 -0.31931804 -0.84807698  0.60596535]
 [-2.01816824  0.74012206  0.52881349 -0.58900053]
 [ 0.18869531 -0.75887206 -0.93323722  0.95505651]
 [ 0.19079432  1.97875732  2.60596728  0.68350889]]


In [37]:
df = pd.DataFrame(data=rand_mat,index='A B C D E'.split(),columns='W X Y Z'.split())
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [38]:
# Accessing a column
mylist = "W X".split()
df['W']
df[mylist]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318
C -2.018168  0.740122
D  0.188695 -0.758872
E  0.190794  1.978757

In [39]:
df["New"] = df["W"] + df["X"]
df

W         X         Y         Z       New
A  2.706850  0.628133  0.907969  0.503826  3.334983
B  0.651118 -0.319318 -0.848077  0.605965  0.331800
C -2.018168  0.740122  0.528813 -0.589001 -1.278046
D  0.188695 -0.758872 -0.933237  0.955057 -0.570177
E  0.190794  1.978757  2.605967  0.683509  2.169552

In [40]:
df.drop('New',axis=1,inplace=True)
df

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [41]:
df.drop('E')

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057

In [42]:
# Selecting rows
df.loc["A"]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [43]:
df.iloc[0]

W    2.706850
X    0.628133
Y    0.907969
Z    0.503826
Name: A, dtype: float64

In [45]:
df.loc[["A","B"],["W","X"]]

W         X
A  2.706850  0.628133
B  0.651118 -0.319318

In [46]:
# Dataframes Part 2

In [47]:
df > 0

W      X      Y      Z
A   True   True   True   True
B   True  False  False   True
C  False   True   True  False
D   True  False  False   True
E   True   True   True   True

In [50]:
df["W"] > 0

A     True
B     True
C    False
D     True
E     True
Name: W, dtype: bool

In [54]:
df[df["W"] > 0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [55]:
cond1 = df["W"] > 0
cond2 = df["Y"] > 1

In [56]:
df[(cond1) & (cond2)]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [57]:
df[(df["W"] > 0) & (df["Y"] > 1) ]

W         X         Y         Z
E  0.190794  1.978757  2.605967  0.683509

In [58]:
df.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [59]:
new_ind = 'CA NY WY OR CO'.split()
print(new_ind)

['CA', 'NY', 'WY', 'OR', 'CO']


In [61]:
df['States'] = new_ind
df

W         X         Y         Z States
A  2.706850  0.628133  0.907969  0.503826     CA
B  0.651118 -0.319318 -0.848077  0.605965     NY
C -2.018168  0.740122  0.528813 -0.589001     WY
D  0.188695 -0.758872 -0.933237  0.955057     OR
E  0.190794  1.978757  2.605967  0.683509     CO

In [63]:
df.set_index('States')

W         X         Y         Z
States                                        
CA      2.706850  0.628133  0.907969  0.503826
NY      0.651118 -0.319318 -0.848077  0.605965
WY     -2.018168  0.740122  0.528813 -0.589001
OR      0.188695 -0.758872 -0.933237  0.955057
CO      0.190794  1.978757  2.605967  0.683509

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, A to E
Data columns (total 5 columns):
W         5 non-null float64
X         5 non-null float64
Y         5 non-null float64
Z         5 non-null float64
States    5 non-null object
dtypes: float64(4), object(1)
memory usage: 400.0+ bytes


In [65]:
df.describe()

W         X         Y         Z
count  5.000000  5.000000  5.000000  5.000000
mean   0.343858  0.453764  0.452287  0.431871
std    1.681131  1.061385  1.454516  0.594708
min   -2.018168 -0.758872 -0.933237 -0.589001
25%    0.188695 -0.319318 -0.848077  0.503826
50%    0.190794  0.628133  0.528813  0.605965
75%    0.651118  0.740122  0.907969  0.683509
max    2.706850  1.978757  2.605967  0.955057

In [67]:
ser_w = df['W'] > 0
ser_w.value_counts()

True     4
False    1
Name: W, dtype: int64

In [68]:
sum(ser_w)

4

## Groupby

In [69]:
import pandas as pd
data = {"Company":['GOOG','GOOG','MSFT','MSFT',"FB","FB"],
"Person":["Sam","Charlie","Amy","Vanessa","Carl","Sarah"],
"Sales":[200,120,340,124,243,350]}

In [71]:
df = pd.DataFrame(data)
df

Company   Person  Sales
0    GOOG      Sam    200
1    GOOG  Charlie    120
2    MSFT      Amy    340
3    MSFT  Vanessa    124
4      FB     Carl    243
5      FB    Sarah    350

In [75]:
df.groupby('Company').describe()

Sales                                                        
        count   mean         std    min     25%    50%     75%    max
Company                                                              
FB        2.0  296.5   75.660426  243.0  269.75  296.5  323.25  350.0
GOOG      2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
MSFT      2.0  232.0  152.735065  124.0  178.00  232.0  286.00  340.0

In [76]:
df.groupby("Company").describe().transpose()

Company              FB        GOOG        MSFT
Sales count    2.000000    2.000000    2.000000
      mean   296.500000  160.000000  232.000000
      std     75.660426   56.568542  152.735065
      min    243.000000  120.000000  124.000000
      25%    269.750000  140.000000  178.000000
      50%    296.500000  160.000000  232.000000
      75%    323.250000  180.000000  286.000000
      max    350.000000  200.000000  340.000000

## operations

In [77]:
df = pd.DataFrame({"col1":[1,2,3,4],"col2":[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [79]:
df['col2'].unique()

array([444, 555, 666], dtype=int64)

In [80]:
df['col2'].nunique()

3

In [81]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

In [85]:
newdf = df[(df['col1'] > 2) & (df['col2'] == 444)]
newdf.head()

col1  col2 col3
3     4   444  xyz

In [86]:
def times_two(number):
    return number*2


In [90]:
df.apply(times_two)

col1  col2    col3  new
0     2   888  abcabc    4
1     4  1110  defdef    8
2     6  1332  ghighi   12
3     8   888  xyzxyz   16

In [91]:
df['new'] = df['col1'].apply(times_two)


In [93]:
df.columns

Index(['col1', 'col2', 'col3', 'new'], dtype='object')

In [94]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
col1    4 non-null int64
col2    4 non-null int64
col3    4 non-null object
new     4 non-null int64
dtypes: int64(3), object(1)
memory usage: 208.0+ bytes


In [97]:
df.describe()

col1        col2       new
count  4.000000    4.000000  4.000000
mean   2.500000  527.250000  5.000000
std    1.290994  106.274409  2.581989
min    1.000000  444.000000  2.000000
25%    1.750000  444.000000  3.500000
50%    2.500000  499.500000  5.000000
75%    3.250000  582.750000  6.500000
max    4.000000  666.000000  8.000000

In [101]:
df.sort_values('col2',ascending=False)

col1  col2 col3  new
2     3   666  ghi    6
1     2   555  def    4
0     1   444  abc    2
3     4   444  xyz    8

In [106]:
df = pd.read_csv('PYTORCH_NOTEBOOKS/00-Crash-Course-Topics/01-Crash-Course-Pandas/example.csv')


In [108]:
new_df = df[['a','b']]
new_df.head()


a   b
0   0   1
1   4   5
2   8   9
3  12  13

In [113]:
newdf.to_csv('mynewcsv.csv',index=False)

In [118]:
df2 = pd.read_excel('PYTORCH_NOTEBOOKS/00-Crash-Course-Topics/01-Crash-Course-Pandas/Excel_Sample.xls',sheet_name="Sheet1")

In [121]:
df = pd.read_html('http://www.fdic.gov/bank/individual/failed/banklist.html')

ImportError: lxml not found, please install it