In [1]:
import torch

In [2]:
import numpy as np

In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
x = torch.from_numpy(arr)

In [6]:
print(type(x))

<class 'torch.Tensor'>


In [7]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5], dtype=torch.int32)

In [8]:
y = torch.as_tensor([1,2,3,4,5])

In [9]:
y.dtype

torch.int64

In [10]:
arr2d = np.arange(0,12).reshape(4,3)
print(arr2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [11]:
x2 = torch.from_numpy(arr2d)
print(x,x.dtype)

tensor([1, 2, 3, 4, 5], dtype=torch.int32) torch.int32


In [12]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5], dtype=torch.int32)


In [13]:
arr2 = np.arange(0,10)

In [14]:
z = torch.tensor(arr2)
print(z)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [15]:
z2 = torch.from_numpy(arr2)
print(z2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


In [16]:
arr2[0] = 99
print(z2)
print(z)

tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)


## Part 2
 Creating a tensor from scratch

In [17]:
new_arr = np.array([1,2,3])

In [18]:
a = torch.tensor(new_arr)
b = torch.Tensor(new_arr)

In [19]:
print(a)
print(b.dtype)

tensor([1, 2, 3], dtype=torch.int32)
torch.float32


In [20]:
torch.empty(4,2)


tensor([[0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 2.0196e-19],
        [2.6563e+20, 6.7407e+22]])

In [21]:
torch.zeros(4,3,dtype=torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [22]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [23]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [24]:
tensor1 = torch.tensor([1,2,3])

In [25]:
tensor1.dtype

torch.int64

In [26]:
tensor1 = tensor1.type(torch.int32)
print(tensor1.dtype)  # type: ignore

torch.int32


In [27]:
torch.rand(4,3)

tensor([[0.6847, 0.0696, 0.8686],
        [0.0330, 0.4744, 0.9195],
        [0.6320, 0.3212, 0.6267],
        [0.0964, 0.2047, 0.0942]])

In [28]:
torch.randn(4,3)

tensor([[ 0.0176, -0.0208,  0.5631],
        [ 0.0968,  0.0283,  0.9452],
        [-0.5032,  0.2258, -0.8232],
        [-0.3163,  0.9752, -1.7599]])

In [29]:
torch.randint(low=0,high=11,size=(5,5))

tensor([[ 3,  5,  9,  0,  1],
        [ 5,  8, 10,  8,  3],
        [10,  1,  9,  2,  5],
        [ 8,  5,  3, 10, 10],
        [ 0,  7,  8,  4,  7]])

In [30]:
x = torch.zeros(2,5)

In [31]:
torch.rand_like(x)

tensor([[0.1269, 0.5710, 0.4960, 0.5475, 0.2195],
        [0.2814, 0.8882, 0.4513, 0.7541, 0.3114]])

In [32]:
torch.randn_like(x)

tensor([[ 0.1360,  0.7519,  0.9328,  1.2183, -0.4606],
        [-0.6094, -1.1841,  0.7079,  1.2064, -2.1184]])

In [33]:
torch.randint_like(x,low=10,high=20)

tensor([[14., 18., 12., 14., 15.],
        [14., 12., 19., 16., 18.]])

In [34]:
# for reproducability

for i in range(4):
    torch.manual_seed(42)
    print(torch.rand(2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])


In [35]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

## Tensor Operations

In [37]:
x = torch.arange(6).reshape(3,2)
print(x)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [38]:
x[1][1]

tensor(3)

In [39]:
x[:,1]

tensor([1, 3, 5])

In [47]:
y = torch.arange(10)
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [48]:
y.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [49]:
y.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [50]:
print(y)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [51]:
z = y.view(2,5)

In [54]:
# Pytorch will infer the correct second dimension
print(y.view(2,-1))
print(y.view(-1,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Arithmetic with Tensor

In [61]:
a = torch.tensor([1.,2.,3.,])
b = torch.tensor([4.,5.,6.,])


In [62]:
print(a.dtype,b.dtype)

torch.float32 torch.float32


In [63]:
print(a+b)

tensor([5., 7., 9.])


In [64]:
# underscore methods
a.mul_(b)
print(a)

tensor([ 4., 10., 18.])


## Matrix Operations

In [65]:
a = torch.tensor([1.,2.,3.,])

In [66]:
# Matrix Multiplication
a.dot(b)

tensor(32.)

In [68]:
a.mul(b)

tensor([ 4., 10., 18.])

In [71]:
d = torch.tensor([[0,2,4],[1,3,5]])
e = torch.tensor([[6,7],[8,9],[10,11]])

torch.mm(d,e)

tensor([[56, 62],
        [80, 89]])

In [72]:
x = torch.tensor([1.,2.,3.,4.,5.])

In [73]:
x.norm()

tensor(7.4162)

In [74]:
x.numel()

5