In [22]:
import torch

In [23]:
x = torch.tensor(2.0,requires_grad=True)

In [24]:
y = 2*x**4 + x**3 + 3*x**2 + 5*x + 1
# defining the function
print(y)

tensor(63., grad_fn=<AddBackward0>)


In [25]:
type(y)

torch.Tensor

In [26]:
y.backward()
# Backpropagating the values

In [27]:
x.grad
# The resulting gradient
# This will be the slope of the polynomial at x = 2

tensor(93.)

More complex back propagation

In [28]:
x = torch.tensor([[1.,2.,3.],[3.,2.,1.]], requires_grad=True)

In [29]:
print(x)

tensor([[1., 2., 3.],
        [3., 2., 1.]], requires_grad=True)


In [30]:
y = 3*x + 2

In [31]:
print(y)

tensor([[ 5.,  8., 11.],
        [11.,  8.,  5.]], grad_fn=<AddBackward0>)


In [33]:
z = 2*y**2 
print(z)

tensor([[ 50., 128., 242.],
        [242., 128.,  50.]], grad_fn=<MulBackward0>)


In [35]:
out = z.mean()
print(out)

tensor(140., grad_fn=<MeanBackward0>)


In [36]:
# Performing back propagation wrt output
out.backward()
print(x.grad)

tensor([[10., 16., 22.],
        [22., 16., 10.]])
