<img src="../Pierian-Data-Logo.PNG">
<br>
<strong><center>Copyright 2019. Created by Jose Marcial Portilla.</center></strong>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [29]:
# CODE HERE
import numpy as np
import torch

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [30]:
# CODE HERE
np.random.seed(42)
torch.manual_seed(42)

### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [31]:
# CODE HERE
arr = np.random.randint(0,5,6)
print(arr)

[3 4 2 4 4 1]


In [32]:
# DON'T WRITE HERE

### 4. Create a tensor "x" from the array above

In [33]:
# CODE HERE
x = torch.from_numpy(arr)
print(x)

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [34]:
# DON'T WRITE HERE

### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [35]:
# CODE HERE
x = x.type(torch.int64)


In [36]:
# DON'T WRITE HERE

### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [37]:
# CODE HERE
x = x.view(3,2)



In [38]:
# DON'T WRITE HERE

### 7. Return the right-hand column of tensor x

In [39]:
# CODE HERE
x[:,1:]


tensor([[4],
        [4],
        [1]])

In [40]:
# DON'T WRITE HERE

### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [41]:
# CODE HERE
print(x*x)


tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [42]:
# DON'T WRITE HERE

### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [55]:
# CODE HERE
torch.manual_seed(42)
y = torch.randint(0,5,(2,3))
print(y)


tensor([[2, 2, 1],
        [4, 1, 0]])


In [47]:
# DON'T WRITE HERE

tensor([[0, 4, 0],
        [3, 3, 4]])


### 10. Find the matrix product of x and y

In [56]:
# CODE HERE
print(x)
print(y)
x.mm(y)

tensor([[3, 4],
        [2, 4],
        [4, 1]])
tensor([[2, 2, 1],
        [4, 1, 0]])


tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])

In [46]:
# DON'T WRITE HERE

## Great job!